// src/index.ts — @meridian-synergy/ui package entry point

export { default as MsLogo   } from './components/MsLogo/MsLogo.vue'
export { default as MsButton } from './components/MsButton/MsButton.vue'
export { default as MsBadge  } from './components/MsBadge/MsBadge.vue'
export { default as MsInput  } from './components/MsInput/MsInput.vue'
export { default as MsCard   } from './components/MsCard/MsCard.vue'
export { default as MsAlert  } from './components/MsAlert/MsAlert.vue'
export { default as MsModal       } from './components/MsModal/MsModal.vue'
export { default as MsSocialLinks } from './components/MsSocialLinks/MsSocialLinks.vue'
export type { SocialLinkItem, SocialNetwork } from './components/MsSocialLinks/MsSocialLinks.vue'
export { default as MsBreadcrumb  } from './components/MsBreadcrumb/MsBreadcrumb.vue'
export type { BreadcrumbItem } from './components/MsBreadcrumb/MsBreadcrumb.vue'
export { default as MsPageHero      } from './components/MsPageHero/MsPageHero.vue'
export { default as MsCtaBanner     } from './components/MsCtaBanner/MsCtaBanner.vue'
export { default as MsSpecGrid      } from './components/MsSpecGrid/MsSpecGrid.vue'
export type { MsSpecItem }            from './components/MsSpecGrid/MsSpecGrid.vue'
export { default as MsValueCard     } from './components/MsValueCard/MsValueCard.vue'
export { default as MsContactBanner  } from './components/MsContactBanner/MsContactBanner.vue'
export type { MsContactAction, MsContactActionType } from './components/MsContactBanner/MsContactBanner.vue'
export { default as MsContactChannel } from './components/MsContactChannel/MsContactChannel.vue'
export type { MsContactChannelType }   from './components/MsContactChannel/MsContactChannel.vue'
export { default as MsSocialCard     } from './components/MsSocialCard/MsSocialCard.vue'
